apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations:
  labels:
    k8slens-edit-resource-version: v2
  name: thingsboard-jsexecutor-hpa
  namespace: thingsboard-qa
spec:
  maxReplicas: 5
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 70
        type: Utilization
    type: Resource
  minReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: thingsboard-jsexecutor
