apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
    meta.helm.sh/release-name: thingsboard
    meta.helm.sh/release-namespace: thingsboard-qa
  creationTimestamp: "2025-09-17T15:50:39Z"
  generation: 8
  labels:
    app.kubernetes.io/instance: thingsboard
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: thingsboard
    app.kubernetes.io/version: 3.5.1
    helm.sh/chart: thingsboard-0.1.4-rc.51
    k10.kasten.io/actionType: snapshot
    k10.kasten.io/appName: thingsboard-qa
    k10.kasten.io/policyName: thingsboard-qa-backup
  name: thingsboard-jsexecutor
  namespace: thingsboard-qa
  resourceVersion: "211005689"
  uid: ead28ff6-66da-46a4-b6ae-378b675a0c7d
spec:
  progressDeadlineSeconds: 600
  replicas: 5
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: thingsboard-jsexecutor
      app.kubernetes.io/name: thingsboard-jsexecutor
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-09-18T06:45:36.088Z"
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: thingsboard-jsexecutor
        app.kubernetes.io/name: thingsboard-jsexecutor
    spec:
      containers:
      - env:
        - name: REMOTE_JS_EVAL_REQUEST_TOPIC
          value: js_eval.requests
        - name: TB_KAFKA_SERVERS
          value: thingsboard-kafka:9092
        - name: TB_QUEUE_KAFKA_REPLICATION_FACTOR
          value: "1"
        - name: LOGGER_LEVEL
          value: info
        - name: LOG_FOLDER
          value: logs
        - name: LOGGER_FILENAME
          value: tb-js-executor-%DATE%.log
        - name: DOCKER_MODE
          value: "true"
        - name: SCRIPT_BODY_TRACE_FREQUENCY
          value: "1000"
        image: docker.io/thingsboard/tb-pe-js-executor:4.0.1PE
        imagePullPolicy: Always
        name: thingsboard
        resources: {}
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: thingsboard
      serviceAccountName: thingsboard
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 5
  conditions:
  - lastTransitionTime: "2025-09-18T06:45:42Z"
    lastUpdateTime: "2025-09-18T06:45:42Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-09-17T15:50:39Z"
    lastUpdateTime: "2025-09-18T06:45:42Z"
    message: ReplicaSet "thingsboard-jsexecutor-5858bdc856" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 8
  readyReplicas: 5
  replicas: 5
  updatedReplicas: 5
