apiVersion: v1
data:
  conf: |
    export JAVA_OPTS="$JAVA_OPTS -Xlog:gc*,heap*,age*,safepoint=debug:file=/var/log/tb-coap-transport/${TB_SERVICE_ID}-gc.log:time,uptime,level,tags:filecount=10,filesize=10M"
    export JAVA_OPTS="$JAVA_OPTS -XX:+IgnoreUnrecognizedVMOptions -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/var/log/tb-coap-transport/${TB_SERVICE_ID}-heapdump.bin"
    export JAVA_OPTS="$JAVA_OPTS -XX:-UseBiasedLocking -XX:+UseTLAB -XX:+ResizeTLAB -XX:+PerfDisableSharedMem -XX:+UseCondCardMark"
    export JAVA_OPTS="$JAVA_OPTS -XX:+UseG1GC -XX:MaxGCPauseMillis=500 -XX:+UseStringDeduplication -XX:+ParallelRefProcEnabled -XX:MaxTenuringThreshold=10"
    export JAVA_OPTS="$JAVA_OPTS -XX:+ExitOnOutOfMemoryError -XX:+UseContainerSupport -XX:MaxRAMPercentage=80"
    export LOG_FILENAME=tb-coap-transport.out
    export LOADER_PATH=/usr/share/tb-coap-transport/conf
  logback: |
    <!DOCTYPE configuration>
    <configuration scan="true" scanPeriod="10 seconds">

        <!-- Console output -->
        <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
            <encoder>
                <pattern>%d{ISO8601} [%thread] %-5level %logger{36} - %msg%n</pattern>
            </encoder>
        </appender>

        <!-- Root logger: keep at INFO to avoid too much noise -->
        <root level="DEBUG">
            <appender-ref ref="STDOUT"/>
        </root>

        <!-- General ThingsBoard logs at INFO -->
        <logger name="org.thingsboard.server" level="DEBUG" />

        <!-- Enable DEBUG for CoAP transport -->
        <logger name="org.thingsboard.server.transport.coap" level="DEBUG" />

        <!-- Enable DEBUG for Kafka queue interactions -->
        <logger name="org.thingsboard.server.queue.kafka" level="DEBUG" />

    </configuration>
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: thingsboard
    meta.helm.sh/release-namespace: thingsboard-qa
  creationTimestamp: "2024-12-05T14:52:06Z"
  labels:
    app.kubernetes.io/instance: thingsboard
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: thingsboard
    app.kubernetes.io/version: 3.5.1
    helm.sh/chart: thingsboard-0.1.4-rc.51
    k8slens-edit-resource-version: v1
    name: thingsboard-coap-transport-config
  name: thingsboard-coap-transport-config
  namespace: thingsboard-qa
  resourceVersion: "211766176"
  uid: 57c65aa2-7da2-4fd9-8f2c-94979114b2f6
