apiVersion: v1
kind: ConfigMap
metadata:
  name: thingsboard-redis-configuration
  namespace: thingsboard-qa
  uid: 4e014e87-b283-485e-97e6-ee4be0a0567a
  resourceVersion: '179538562'
  creationTimestamp: '2024-12-05T14:52:06Z'
  labels:
    app.kubernetes.io/instance: thingsboard
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: redis
    app.kubernetes.io/version: 6.2.6
    helm.sh/chart: redis-16.4.5
    k8slens-edit-resource-version: v1
  annotations:
    meta.helm.sh/release-name: thingsboard
    meta.helm.sh/release-namespace: thingsboard-qa
  selfLink: /api/v1/namespaces/thingsboard-qa/configmaps/thingsboard-redis-configuration
spec: {}
data:
  master.conf: |-
    dir /data
    # User-supplied master configuration:
    rename-command FLUSHALL ""
    # End of master configuration
  redis.conf: |-
    # User-supplied common configuration:
    # Enable AOF https://redis.io/topics/persistence#append-only-file
    appendonly yes
    # Disable RDB persistence, AOF persistence already enabled.
    save ""
    # End of common configuration
    auto-aof-rewrite-percentage 100
    auto-aof-rewrite-min-size 32mb
    maxmemory 8gb
    maxmemory-policy allkeys-lru
    tcp-keepalive 60
  replica.conf: |-
    dir /data
    slave-read-only yes
    # User-supplied replica configuration:
    rename-command FLUSHDB ""
    rename-command FLUSHALL ""
    # End of replica configuration
