apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: thingsboard
    meta.helm.sh/release-namespace: thingsboard-qa
  labels:
    app.kubernetes.io/component: zookeeper
    app.kubernetes.io/instance: thingsboard
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: zookeeper
    app.kubernetes.io/version: 3.8.0
    helm.sh/chart: zookeeper-10.2.5
  name: thingsboard-zookeeper-headless
  namespace: thingsboard-qa
spec:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: tcp-client
    port: 2181
    protocol: TCP
    targetPort: client
  - name: tcp-follower
    port: 2888
    protocol: TCP
    targetPort: follower
  - name: tcp-election
    port: 3888
    protocol: TCP
    targetPort: election
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/component: zookeeper
    app.kubernetes.io/instance: thingsboard
    app.kubernetes.io/name: zookeeper
  sessionAffinity: None
  type: ClusterIP
