apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/publicEndpoints: "null"
    meta.helm.sh/release-name: thingsboard
    meta.helm.sh/release-namespace: thingsboard-qa
  labels:
    app.kubernetes.io/instance: thingsboard
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: thingsboard
    app.kubernetes.io/version: 3.5.1
    helm.sh/chart: thingsboard-0.1.4-rc.51
    k8slens-edit-resource-version: v1
  name: thingsboard-mqtt
  namespace: thingsboard-qa
spec:
  - 172.20.207.154
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: mqtt
    port: 1883
    protocol: TCP
    targetPort: mqtt
  - name: mqtts
    port: 1884
    protocol: TCP
    targetPort: 1884
  selector:
    app.kubernetes.io/instance: thingsboard-mqtt
    app.kubernetes.io/name: thingsboard-mqtt
  sessionAffinity: None
  type: ClusterIP
