apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: thingsboard
    meta.helm.sh/release-namespace: thingsboard-qa
  labels:
    app.kubernetes.io/component: master
    app.kubernetes.io/instance: thingsboard
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: redis
    app.kubernetes.io/version: 6.2.6
    helm.sh/chart: redis-16.4.5
  name: thingsboard-redis-master
  namespace: thingsboard-qa
spec:
  - 172.20.148.163
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: tcp-redis
    port: 6379
    protocol: TCP
    targetPort: redis
  selector:
    app.kubernetes.io/component: master
    app.kubernetes.io/instance: thingsboard
    app.kubernetes.io/name: redis
  sessionAffinity: None
  type: ClusterIP
