apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: thingsboard
    meta.helm.sh/release-namespace: thingsboard-qa
  labels:
    app.kubernetes.io/instance: thingsboard
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: cassandra
    app.kubernetes.io/version: 4.0.3
    helm.sh/chart: cassandra-9.1.8
  name: thingsboard-cassandra
  namespace: thingsboard-qa
spec:
  - 172.20.26.0
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: cql
    port: 9042
    protocol: TCP
    targetPort: cql
  - name: metrics
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: thingsboard
    app.kubernetes.io/name: cassandra
  sessionAffinity: None
  type: ClusterIP
