apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: thingsboard-zookeeper
  namespace: thingsboard-qa
  uid: 3df8a724-9e4c-46d8-8dff-8123390ad1a4
  resourceVersion: '194802287'
  generation: 113
  creationTimestamp: '2024-12-05T14:52:06Z'
  labels:
    app.kubernetes.io/component: zookeeper
    app.kubernetes.io/instance: thingsboard
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: zookeeper
    app.kubernetes.io/version: 3.8.0
    helm.sh/chart: zookeeper-10.2.5
    k10.kasten.io/actionType: snapshot
    k10.kasten.io/appName: thingsboard-qa
    k10.kasten.io/policyName: thingsboard-qa-backup
    k8slens-edit-resource-version: v1
    role: zookeeper
  annotations:
    meta.helm.sh/release-name: thingsboard
    meta.helm.sh/release-namespace: thingsboard-qa
  selfLink: /apis/apps/v1/namespaces/thingsboard-qa/statefulsets/thingsboard-zookeeper
status:
  observedGeneration: 113
  replicas: 3
  readyReplicas: 3
  currentReplicas: 3
  updatedReplicas: 3
  currentRevision: thingsboard-zookeeper-67bfbbdfcb
  updateRevision: thingsboard-zookeeper-67bfbbdfcb
  collisionCount: 0
  availableReplicas: 3
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/component: zookeeper
      app.kubernetes.io/instance: thingsboard
      app.kubernetes.io/name: zookeeper
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: zookeeper
        app.kubernetes.io/instance: thingsboard
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: zookeeper
        app.kubernetes.io/version: 3.8.0
        helm.sh/chart: zookeeper-10.2.5
      annotations:
        kubectl.kubernetes.io/restartedAt: '2025-08-28T13:47:54.500Z'
    spec:
      volumes:
        - name: scripts
          configMap:
            name: thingsboard-zookeeper-scripts
            defaultMode: 493
      containers:
        - name: zookeeper
          image: docker.io/bitnami/zookeeper:3.8.4-debian-12-r9
          command:
            - /scripts/setup.sh
          ports:
            - name: client
              containerPort: 2181
              protocol: TCP
            - name: follower
              containerPort: 2888
              protocol: TCP
            - name: election
              containerPort: 3888
              protocol: TCP
          env:
            - name: BITNAMI_DEBUG
              value: 'false'
            - name: ZOO_DATA_LOG_DIR
            - name: ZOO_PORT_NUMBER
              value: '2181'
            - name: ZOO_TICK_TIME
              value: '2000'
            - name: ZOO_INIT_LIMIT
              value: '10'
            - name: ZOO_SYNC_LIMIT
              value: '5'
            - name: ZOO_PRE_ALLOC_SIZE
              value: '65536'
            - name: ZOO_SNAPCOUNT
              value: '100000'
            - name: ZOO_MAX_CLIENT_CNXNS
              value: '60'
            - name: ZOO_4LW_COMMANDS_WHITELIST
              value: srvr, mntr, ruok
            - name: ZOO_LISTEN_ALLIPS_ENABLED
              value: 'no'
            - name: ZOO_AUTOPURGE_INTERVAL
              value: '0'
            - name: ZOO_AUTOPURGE_RETAIN_COUNT
              value: '3'
            - name: ZOO_MAX_SESSION_TIMEOUT
              value: '40000'
            - name: ZOO_SERVERS
              value: >-
                thingsboard-zookeeper-0.thingsboard-zookeeper-headless.thingsboard-qa.svc.cluster.local:2888:3888::1
                thingsboard-zookeeper-1.thingsboard-zookeeper-headless.thingsboard-qa.svc.cluster.local:2888:3888::2
                thingsboard-zookeeper-2.thingsboard-zookeeper-headless.thingsboard-qa.svc.cluster.local:2888:3888::3
            - name: ZOO_ENABLE_AUTH
              value: 'no'
            - name: ZOO_ENABLE_QUORUM_AUTH
              value: 'no'
            - name: ZOO_HEAP_SIZE
              value: '1024'
            - name: ZOO_LOG_LEVEL
              value: ERROR
            - name: ALLOW_ANONYMOUS_LOGIN
              value: 'yes'
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
          volumeMounts:
            - name: scripts
              mountPath: /scripts/setup.sh
              subPath: setup.sh
            - name: data
              mountPath: /bitnami/zookeeper
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - '-c'
                - echo "ruok" | timeout 2 nc -w 2 localhost 2181 | grep imok
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 6
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - '-c'
                - echo "ruok" | timeout 2 nc -w 2 localhost 2181 | grep imok
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 6
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 1001
            runAsNonRoot: true
            allowPrivilegeEscalation: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: thingsboard-node-sa
      serviceAccount: thingsboard-node-sa
      securityContext:
        fsGroup: 1001
      subdomain: thingsboard-zookeeper-headless
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/component: zookeeper
                    app.kubernetes.io/instance: thingsboard
                    app.kubernetes.io/name: zookeeper
                topologyKey: kubernetes.io/hostname
      schedulerName: default-scheduler
  volumeClaimTemplates:
    - kind: PersistentVolumeClaim
      apiVersion: v1
      metadata:
        name: data
        creationTimestamp: null
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 8Gi
        volumeMode: Filesystem
      status:
        phase: Pending
  serviceName: thingsboard-zookeeper-headless
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  revisionHistoryLimit: 10
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
